repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: master
    hooks:
      - id: autopep8
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: flake8
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: '^.+?\.json$'
default_language_version:
  python: python3.6
files: '^.+?\.py$'
exclude: 'static/|media/|migrations/'
